remove script as does not work in remote scenario

diff --git a/actions/smoke-test/action.yaml b/actions/smoke-test/action.yaml
--- a/actions/smoke-test/action.yaml
+++ b/actions/smoke-test/action.yaml
@@ -14,4 +14,24 @@ runs:
 
   steps:
     - shell: bash
-      run: sh ./actions/smoke-test/action.sh ${{ inputs.version }} ${{ inputs.wait_interval }}
+      run: |
+        version=${{ inputs.version }}
+        wait_interval=${{ inputs.wait_interval }}
+        iterations=3
+        health_endpoint="https://81445a13a4f840ffabc16875eca58ab7.api.mockbin.io/"
+        
+        for i in $(seq 1 $iterations); do
+          current_version=$(curl -s "$health_endpoint" | jq -r '.version')
+
+          echo "checking new: ${version} against current: ${current_version} ($i of $iterations)"
+        
+          if [ "$current_version" = "$version" ]; then
+            echo "successfully matched version"
+            exit 0
+          else
+            sleep ${wait_interval}
+          fi
+        done
+        
+        echo "failed to verify the deployed version of server"
+        exit 1
